---
# defaults file for roles/mariadb

mariadb_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql


mariadb_hosts:
  - 127.0.0.1
  - ::1
  - "{{ ansible_nodename }}"
  - "%"
  - localhost


