---
# tasks file for roles/common

- name: "Update package cache"
  ansible.builtin.command: "{{ 'apt update' if ansible_os_family == 'Debian' else 'dnf makecache' }}"
  changed_when: false

- name: "Set Apache service name"
  set_fact:
    apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

- name: "Install common packages"
  ansible.builtin.package:
    state: "present"
    name: "{{ common_packages }}"


- name: "Add group for our users"
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: "{{ item.state }}"
  with_items: "{{ users }}"

- name: "Add users to our group"
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    comment: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ users }}"


